// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1S4j5uVuukMMJbfquI1NE0CqAnEGtK_g',
    appId: '1:324328357412:web:82269850ecba21b13aa2b1',
    messagingSenderId: '324328357412',
    projectId: 'callnaija',
    authDomain: 'callnaija.firebaseapp.com',
    storageBucket: 'callnaija.firebasestorage.app',
    measurementId: 'G-D3544DBSZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEGAnaWJXl2tMYehtzhtVidQljMYZM6e0',
    appId: '1:324328357412:android:763806fa446e58203aa2b1',
    messagingSenderId: '324328357412',
    projectId: 'callnaija',
    storageBucket: 'callnaija.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtHu4KRE7UVFdzgNV0qOvdbeuTjdG1uvc',
    appId: '1:324328357412:ios:dd08197e66e6f5d63aa2b1',
    messagingSenderId: '324328357412',
    projectId: 'callnaija',
    storageBucket: 'callnaija.firebasestorage.app',
    iosBundleId: 'com.example.callnaija',
  );
}
